language: node_js

node_js:
  - node

branches:
  only:
    - master
    - /^dev|\/dev$/

install:
  - npm ci

stages:
  - build
  - test
  - functional_tests
  
jobs:
  include:    
    - stage: build
      env: JOB="Build"
      script: npm run build

    - stage: test
      env: JOB="Mocha unit tests"
      script: npm run codecov

    - stage: test
      env: JOB="Tslint"
      script: npm run tslint

    - stage: functional_tests
      env: JOB="Functional Tests"
      script: npm run test-functional
