version: "#{build}"
clone_depth: 1

branches:
  only:
    - master
    - dev

environment:
  nodejs_version: "stable"

install:
  - npm install
  - node --version
  - npm --version
build: off

test_script:
  - npm run build
  - npm test
