version: "#{build}"
clone_depth: 1

branches:
  only:
    - master
    - dev

environment:
  nodejs_version: "stable"
  matrix:
  - current_test_script: test
  - current_test_script: tslint


install:
  - npm install
  - node --version
  - npm --version
build: off

test_script:
  - ps: npm run build
  - ps: npm run $env:current_test_script
