version: "#{build}"
clone_depth: 1

branches:
  only:
    - master
    - /^dev|\/dev$/

environment:
  nodejs_version: "Current"
  matrix:
  - current_test_script: test
  - current_test_script: tslint
  - current_test_script: test-functional

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm ci
build: off

test_script:
  - npm run build
  - npm run %current_test_script%
